cp jmp-address/libs/instructions.js none/libs/
cp jmp-address/libs/instructions.js or-reg-with-reg/libs/
cp jmp-address/libs/instructions.js shl-number-with-reg/libs/
cp jmp-address/libs/instructions.js mov-reg-to-regaddress/libs/
cp jmp-address/libs/instructions.js dec-reg/libs/
cp jmp-address/libs/instructions.js xor-address-with-reg/libs/
cp jmp-address/libs/instructions.js div-reg/libs/
cp jmp-address/libs/instructions.js mov-address-to-reg/libs/
cp jmp-address/libs/instructions.js jz-address/libs/
cp jmp-address/libs/instructions.js div-regaddress/libs/
cp jmp-address/libs/instructions.js and-reg-with-reg/libs/
cp jmp-address/libs/instructions.js cmp-reg-with-reg/libs/
cp jmp-address/libs/instructions.js cmp-address-with-reg/libs/
cp jmp-address/libs/instructions.js jnz-address/libs/
cp jmp-address/libs/instructions.js sub-regaddress-from-reg/libs/
cp jmp-address/libs/instructions.js or-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js shr-address-with-reg/libs/
cp jmp-address/libs/instructions.js or-address-with-reg/libs/
cp jmp-address/libs/instructions.js mov-reg-to-reg/libs/
cp jmp-address/libs/instructions.js add-regaddress-to-reg/libs/
cp jmp-address/libs/instructions.js div-address/libs/
cp jmp-address/libs/instructions.js shl-address-with-reg/libs/
cp jmp-address/libs/instructions.js and-number-with-reg/libs/
cp jmp-address/libs/instructions.js add-reg-to-reg/libs/
cp jmp-address/libs/instructions.js push-address/libs/
cp jmp-address/libs/instructions.js cmp-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js or-number-with-reg/libs/
cp jmp-address/libs/instructions.js sub-address-from-reg/libs/
cp jmp-address/libs/instructions.js mul-number/libs/
cp jmp-address/libs/instructions.js mul-regaddress/libs/
cp jmp-address/libs/instructions.js mov-number-to-reg/libs/
cp jmp-address/libs/instructions.js jc-regaddress/libs/
cp jmp-address/libs/instructions.js shr-reg-with-reg/libs/
cp jmp-address/libs/instructions.js shr-number-with-reg/libs/
cp jmp-address/libs/instructions.js not-reg/libs/
cp jmp-address/libs/instructions.js shl-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js and-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js cmp-number-with-reg/libs/
cp jmp-address/libs/instructions.js and-address-with-reg/libs/
cp jmp-address/libs/instructions.js jnc-regaddress/libs/
cp jmp-address/libs/instructions.js add-number-to-reg/libs/
cp jmp-address/libs/instructions.js sub-reg-from-reg/libs/
cp jmp-address/libs/instructions.js ja-address/libs/
cp jmp-address/libs/instructions.js push-number/libs/
cp jmp-address/libs/instructions.js add-address-to-reg/libs/
cp jmp-address/libs/instructions.js mov-regaddress-to-reg/libs/
cp jmp-address/libs/instructions.js mov-reg-to-address/libs/
cp jmp-address/libs/instructions.js jna-address/libs/
cp jmp-address/libs/instructions.js shl-reg-with-reg/libs/
cp jmp-address/libs/instructions.js push-regaddress/libs/
cp jmp-address/libs/instructions.js inc-reg/libs/
cp jmp-address/libs/instructions.js jmp-regaddress/libs/
cp jmp-address/libs/instructions.js ja-regaddress/libs/
cp jmp-address/libs/instructions.js jc-address/libs/
cp jmp-address/libs/instructions.js call-address/libs/
cp jmp-address/libs/instructions.js mul-reg/libs/
cp jmp-address/libs/instructions.js mov-number-to-address/libs/
cp jmp-address/libs/instructions.js jnz-regaddress/libs/
cp jmp-address/libs/instructions.js call-regaddress/libs/
cp jmp-address/libs/instructions.js xor-number-with-reg/libs/
cp jmp-address/libs/instructions.js jnc-address/libs/
cp jmp-address/libs/instructions.js push-reg/libs/
cp jmp-address/libs/instructions.js pop-reg/libs/
cp jmp-address/libs/instructions.js xor-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js mul-address/libs/
cp jmp-address/libs/instructions.js jna-regaddress/libs/
cp jmp-address/libs/instructions.js shr-regaddress-with-reg/libs/
cp jmp-address/libs/instructions.js ret/libs/
cp jmp-address/libs/instructions.js sub-number-from-reg/libs/
cp jmp-address/libs/instructions.js jz-regaddress/libs/
cp jmp-address/libs/instructions.js div-number/libs/
cp jmp-address/libs/instructions.js mov-number-to-regaddress/libs/
cp jmp-address/libs/instructions.js xor-reg-with-reg/libs/
